### ISSUE TITLE
Please support non-absolute paths

### ISSUE THREAD

**Issue by rrthomas** [AmaiKinono/citre#37]
If paths are not absolute, and the `TAG_PROC_CWD` pseudo-tag is not given (not supported by some tags programs), could citre reasonably assume that the paths are relative to the directory containing the `tags` file?

This would make citre compatible with automake, which allows automatic generation of tags files, but only with relative paths (when not using universal-ctags).

**Comment by AmaiKinono** [comment]
This is something I've thought of, but didn't come up with a conclusion.

First of all, Citre detects if a tags file uses relative path on its first line. This is not very robust if a source file outside of the working dir is feed to ctags. This need to be improved.

> could citre reasonably assume that the paths are relative to the directory containing the `tags` file?

It looks like a reasonable assumption, but not always true... I also thought of ask the user for the root directory, but that would be annoying since it need to be done on every new Emacs session.

When `TAG_PROC_CWD` is not presented, an approach that should be good is:

- Once we get a tag with relative path, assume the root path is where `tags` file is in, and check if the file exists.
- If it exists, we use it as the root path for the whole tags file. There is a chance of mistake, i.e., it happens to be a irrelevant file that just exists there, but the chance is low.
- If it doesn't exist, we ask the user for the root path.

This may need some rework on the infrastructure.

> ...but only with relative paths (when not using universal-ctags).

Well, actually u-ctags is Citre's only target (or I won't use `readtags`), and now u-ctags generates `TAG_PROC_CWD` by default. For Citre + u-ctags users, they may use other language-specific tools to generate tags file (like ripper-tags or rusty-tags), which doesn't contain `TAG_PROC_CWD`, and readtags should work for them too. I think it's meaningful to support such situations. But I'd say appending a pseudo tag to a tags file using command line tools is not very hard, and this could be a workaround.

Overall, my opinion is we should improve the relative path detection for tags files. Then, if handling missing `TAG_PROC_CWD` is trivial, I'll do it.

**Comment by rrthomas** [comment]
I agree that it's reasonable to assume that paths are relative to the `tags` file (and if not, prompt the user). This is what Emacs seems to do.

**Comment by AmaiKinono** [comment]
Note for myself: For detecting relative path, we could write a predicate (using `prefix?` or regexp) of whether a path is relative, and use readtags to filter them out. The problem is:

- What does absolute/relative paths in tags file look like under Windows?
- Is the speed acceptable for a huge tags file like in the linux kernel?

**Comment by rrthomas** [comment]
There are Elisp functions to manage filenames, and convert between Unix & Windows, I don't think you have to reinvent this stuff!

**Comment by AmaiKinono** [comment]
> There are Elisp functions to manage filenames, and convert between Unix & Windows

Thanks for the tip. I found `convert-standard-filename`, but I still have to do some test (later).
